PRO GETPIX, HEAD, PIXEL=PIXEL
;
; RETURN PIXLE SCALE IN ARCSEC
;
;
EXTAST, HEAD, AST, NOPARAMS
;PRINT, NOPARAMS


IF (NOPARAMS EQ 1 OR NOPARAMS EQ 3) THEN BEGIN
    ;PRINT, 'NOPARAM=1 OR 3. CDELT IS AVAILABLE IN THE HEADER   '
    
    CDELT = SXPAR(HEAD, 'CDELT*')
    PIXEL = ABS(CDELT[0]) * 3600.
ENDIF


IF (NOPARAMS EQ 2) THEN BEGIN 
    ;PRINT, 'NOPARAM=2. CD*_* IS AVAILABLE IN THE HEADER        '
    
    PIXEL = SQRT(AST.CD[0]^2 + AST.CD[1]^2) * 3600.
ENDIF

END
