PRO JB2JP, HEAD, FWHM=FWHM, BMPPX=BMPPX, PXPBM=PXPBM
;
; FWHM IS IN ARCSEC
; CONVERT 'JY/BEAM' TO JY/PIX
; BMPPX = BEAM/PIXEL
; PXPBM = PIXEL/BEAM
;
EXTAST, HEAD, AST, NOPARAMS
GETPIX, HEAD, PIXEL=PIXEL
;
PIXAREA= PIXEL * PIXEL
BMPPX  = PIXAREA/(1.1331*FWHM^2)
;
PXPBM = 1./BMPPX
END
